# use Ganache's forked mainnet mode as the default network (mainnet-fork)
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: optimism-dev-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.6
  - OpenZeppelin/openzeppelin-contracts@4.7.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "@yearnvaults=yearn/yearn-vaults@0.4.6"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1"
      - "@oz34=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@oz_ug=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3"

reports:
  exclude_contracts:
    - Math
    - Vault
    - Ownable
    - Address
    - BaseStrategy
    - SafeERC20
